docs/public/_redirects

This PR fixes the issue number: no issue.
- Adds redirects for paths like `/codeflow` and `/guides/user-guide` to actual pages (the first page of each section).

Add redirects for top-level paths that don't have a page

---

.vitepress/theme/index.ts
.vitepress/theme/scripts/edit-link.ts

This PR fixes the issue number: n.a.
- Moved the script we used to hack the URL of the "Edit this page" links from the theme's main config file to a dedicated script.
- Fixed TypeScript issues without using `(event: any)`.

Move edit link hack to a dedicated script module

---

.vitepress/theme/styles/fixes.scss

This PR fixes the issue number:  #52 
- remove `background-color` transitions
Would you like your contribution to be celebrated? Please check all that apply: 
(~idk 😅) I was testing out codeflow 

fix: remove background color transitions from dark/light switch 

---

.vitepress/config.ts
package-lock.json
package.json

This PR fixes the issue number: n.a.
Add support for Markdown footnotes, using the Pandoc footnotes syntax:
```markdown
Hello World[^1].
[^1]: In its most general sense, the term "world" refers to the totality of entities, to the whole of reality or to everything that is.
```
The footnote content can be placed at the end of an article, or inline in the content (in between paragraphs); it will always be rendered at the end.
⚡️ ⚡️ ⚡️  Thank you for contributing to StackBlitz …

Add support for Markdown footnotes (Pandoc-style)

---

.vitepress/theme/styles/colors.scss
.vitepress/theme/styles/content.scss
docs/playground/test-page.md
package-lock.json
package.json

This PR fixes the issue number: SBPF-2713
- Update Vitepress
- Create a demo page for Markdown styles
- Fix some contrast issues with warning/info blocks (reported by @AleksandrSl)
I made sure that all contrasts passed WCAG 2 ratios (4.5:1 or above required -> I think everything is now at least 5:1 or above). We had some 4.4:1, and one very low contrast ratio (warning text in the light theme).
The "info" blocks didn't need more contrast as per WCAG 2, but I still felt that in practice they looked muted, and we are putting important information there in many pages so a muted “this is not important” look felt wrong. So I upped that contrast a bit (light theme) or significantly (dark theme).
Try it live: https://deploy-preview-68--stackblitz-docs.netlify.app/playground/test-page
Before/after …

fix: improve contrast of custom containers

---

docs/guides/integration/embedding.md

This PR fixes the issue number: n.a.
This PR changes the case of documented URL query parameters to the case used by StackBlitz Enterprise Edition.
While `stackblitz.com` treats URL query parameters as case-insensitive, older StackBlitz EE deployments do not. Checking the code used in StackBlitz EE, it looks like the following parameters should be all lowercase:
- `devToolsHeight` -> `devtoolsheight`
- `hideDevTools` -> `hidedevtools`
- `initialPath` -> `initialpath`
Other parameters such as `hideExplorer` do use camel-case, and are documented with the correct case.
We just shipped a related fix to `@stackblitz/sdk` (no changes to the SDK docs required):
https://github.com/stackblitz/core/pull/2154
Would you like your contribution to be celebrated? Please …

fix: backwards-compatible case for URL query params

---

docs/codeflow/content-updates-with-web-publisher.md

Updating the web publisher page so that the "Edit in Web Publisher" button takes you into web publisher to edit that page. I did this since we link to this page from the Webcontainer API blog post and I tried to click this button to see what the Web Publisher experience was like and it wasn't hyperlinked and I was disappointed as a naive user
- Adding a link to https://pr.new/stackblitz/docs/edit/main/docs/codeflow/content-updates-with-web-publisher.md to the "Edit in Web Publisher" button that sits on that page
- [? ] My code follows the style guidelines of this project
- [ X] I have reviewed my code or content update and edited it to the best of my abilities
- [ X] I have commented my code, particularly in hard-to-understand areas; my comments are concise …

Making the Web Publisher docs page more engaging for new users

---

netlify.toml

This PR updates the netlify deployment so that images are served with a `CORP: cross-origin` header. This allows the images to be used on cross-origin isolated websites.
The problem is that the images are not served with a `CORP` header. This means that they cannot be used on websites that are cross-origin isolated.

fix: serve images with corp header

---

docs/platform/webcontainers/browser-support.md

Important update about Safari 16.4 TP.
- Changed the page description
- Changed the Safari section
- Added mention of safari in "Web Platform requirements"
-----
<a href="https://stackblitz.com/~/github.com/stackblitz/docs/tree/web-publisher/sylwiavargas/browser-support"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Submitted with [StackBlitz Web Publisher](https://developer.stackblitz.com/codeflow/integrating-web-publisher)._

Update browser support page

---

docs/platform/webcontainers/browser-support.md

Missing `alpha -> beta` change from PR #102
-----
<a href="https://stackblitz.com/~/github.com/stackblitz/docs/tree/web-publisher/Nemikolh/browser-support"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Submitted with [StackBlitz Web Publisher](https://developer.stackblitz.com/codeflow/integrating-web-publisher)._

Nit: Firefox support is beta in the TLDR but not in the Firefox section

---

.vitepress/config.ts
docs/links.ts

This PR is a follow-up to #104.
When we redesigned our docs in September 2022 we wanted to have specific sidebars for each section of top-level content, and in particular we wanted to put the Enterprise Edition content in its own sidebar.
In #104 we changed that to have a single sidebar with all the docs content, including the Enteprise Edition-specific content, in collapsible sections, to be consistent with the https://webcontainers.io docs.
This PR undoes part of this change, by putting the Enterprise Edition sidebar content back in its own group.
Main sidebar (no EE section):
EE-specific sidebar:
- we usually link github profile pic -- …

Separate the Enterprise Edition sidebar from the main content

---

docs/guides/integration/open-from-github.md

We now support changing where StackBlitz will look up for config file by appending `configPath` in the URL. 
So I'm adding its docs 🙇 

feat: add docs for `configPath`

---

.vitepress/theme/scripts/gtag.ts
package-lock.json
package.json

This PR fixes the issue number: #129
- Removes the `@types/gtag.js` npm package, which was used only minimally to get autocompletion for the `window.gtag` function.
- Add a custom type for `window.gtag` in the only function that uses it.
- Now this project installs in Codeflow IDE even if you have an ad blocker that tries to block URLs containing `/gtag.js`.
⚡️ ⚡️ ⚡️  Thank you for contributing to StackBlitz ⚡️ ⚡️ ⚡️ 
-----
<a …

Remove @types/gtag.js dep which fails in Codeflow

---

docs/links.ts

This fixes the case studies link to link to the new page
-----
<a href="https://stackblitz.com/~/github/stackblitz/docs/tree/samdenty%2Ffix-case-studies"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github/stackblitz/docs/tree/samdenty%2Ffix-case-studies)._

fix: case studies page

---

docs/links.ts

replaces expired discord invite link with permanent link from footer

fix broken discord link

---

.vitepress/config.ts

#159 contained a typo where we changed the name of the Algolia index from `'stackblitz'` to `'webcontainers'` (I suppose it was copied from the https://webcontainers.io docs source), which broke our docs search for the past couple weeks.

Fix Algolia config

---

.vitepress/theme/components/Feedback/Feedback.vue

We forgot to update the name in form (it should be matched with this [form-name](https://github.com/stackblitz/docs/blob/a3586ca7371d42fd949a1305a04594707342945c/.vitepress/theme/components/Feedback/Feedback.vue#L56)). You can test it on preview, if you send a feedback, the post request should return 200 instead of 404, and you can find the results under Sites > developer.stackblitz.com > Forms on Netlify.

fix: use the correct form name to send feedback to Netlify 

---

.vitepress/config.ts
README.md

In https://github.com/stackblitz/docs/pull/189 I’m renaming the incorrectly named `VITE_GTM_ID` to `VITE_GTAG_ID`, and using `VITE_GTM_ID` for an actual Google Tag Manager id.
This PR does this renaming only (without any other change), so that we can make both production and preview deploys using the same environment configuration.

chore: rename VITE_GTM_ID env var to VITE_GTAG_ID

---

.vitepress/config.ts
README.md

Fixes MKT-69.
This PR updates the analytics snippet code to load both `/gtm.js` and `/gtag/js`.

feat: use Google Tag Manager gtm.js instead of gtag.js

---

.vitepress/theme/components/AuthButtons/AuthButtons.vue
.vitepress/theme/components/AuthButtons/linkStyles.scss

The correct size is 36px and it now gets a bit bigger 🌱
-----
<a href="https://stackblitz.com/~/github/stackblitz/docs/tree/ykmsd%2Fpatch-41300"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github/stackblitz/docs/tree/ykmsd%2Fpatch-41300)._

Fix the height of auth buttons

---

docs/platform/webcontainers/browser-config.md
docs/platform/webcontainers/browser-support.md

This PR adds a note about firefox private browsing limiting the capabilities of WebContainers.

feat(firefox): add warning about firefox private browsing

---

docs/teams/setting-up-your-team.md

- Adds instructions for deleting a team per PRO-1278
- Reorganizes page structure with new h2s
-----
<a href="https://stackblitz.com/~/github.com/stackblitz/docs/tree/web-publisher/peter-zawistowicz/setting-up-your-team.md"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz next generation editor" align="left" width="103" height="20"></a> _Submitted with [StackBlitz Web Publisher](https://developer.stackblitz.com/codeflow/integrating-web-publisher)._

Add docs for deleting a team

---

docs/enterprise/configuring-dns.md

Remove the need to configure a `*.preview` wildcard subdomain.
In newer versions of StackBlitz enterprise this is no longer needed.

Update DNS wildcard documentation

---

.vitepress/theme/components/Helpers/CardLink.vue
.vitepress/theme/components/HomeIntro.vue
.vitepress/theme/components/Icons/SvgIcon.vue
.vitepress/theme/styles/custom-block.scss
package-lock.json
package.json

Our icons on the home page are working correctly in development mode, but not in the final build.
The icons end up as data URLs in the HTML build, with the SVG attributes quoted with single quotes (instead of double quotes in the source files). And we render those URLs with:
```js
const style = `--icon: url('${url}');`
```
Which breaks when the `url` is something like:
```
data:image/svg+xml,%3csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20512%20512'%3e…%3c/svg%3e
```
I added some logic to use double quotes when the URL contains single quotes.

Fix home page icons
